# trust x-forwarded-proto
server.forward-headers-strategy=framework

# 5173 in dev
app.frontend-url=/

# baseUrl should be https://aoty.dedyn.io and registrationId should be spotify
spring.security.oauth2.client.registration.spotify.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# we are not dealing with migrations today
spring.jpa.hibernate.ddl-auto=update

server.error.include-message=never
server.error.include-stacktrace=never
